### ISSUE TITLE
uilabel example

### ISSUE THREAD

**Issue by tophfer** [AliSoftware/OHAttributedLabel#1]
Hello .. I was wondering if you could provide an example of how to attach the attributed string to a uilabel. I've been trying and I keep getting the error :

error: request for member 'attributedText' in something not a structure or union

Thanks

**Comment by AliSoftware** [comment]
Hello,

You can find an example in the SampleCode.m file.
Of course it is only an extract of code fragments, not a whole example project.

If you get such an error, it is probably because your compiler does not known about the UIAttributedLabel: maybe you forgot to #import "OHAttributedLabel.h"?

**Comment by tophfer** [comment]
yeah thanks ... I figured it out ... works great !!!!

**Comment by AliSoftware** [comment]
Hi tophfer,

Just to notify you that I added a more complete example (a real Xcode projet and not just the SampleCode.m file) if you need.
I also fixed some leaks in the code.
