### ISSUE TITLE
Duplicate Symbol UIColorFromString

### ISSUE THREAD

**Issue by johntmcintosh** [AliSoftware/OHAttributedLabel#100]
Installed OHAttributedLabel today through CocoaPods and got a duplicate symbol linker error. Turns out that both this project and [MagicalRecord](https://github.com/magicalpanda/MagicalRecord) have a UIColorFromString function. 

What would you think about renaming this function to something like `OHUIColorFromString()` so that it's namespaced to avoid such collisions?

I'll probably make a fork in a few minutes so I can get both libraries running in my project and will submit a pull request that you're welcome to accept or deny. Just wanted to give a little background on what it's about.

BTW - Been using OHAttributedLabel in a couple of projects and it's fantastic. Really appreciate you sharing this with us.

Thanks! 1

**Comment by AliSoftware** [comment]
Thanks for this suggestion and fork, I've just merged it!

Glad my library is useful for you. If you like it, don't hesitate to give me some details about your application(s) that uses OHAL (name and AppStore link) so I could add it to my [dedicated wiki page](https://github.com/AliSoftware/OHAttributedLabel/wiki/They-use-this-class) :wink:

**Comment by AliSoftware** [comment]
Note: [version tagged to 3.2.1](https://github.com/AliSoftware/OHAttributedLabel/wiki/Revisions-History) to include this merge. You may update your CocoaPod specs.

**Comment by johntmcintosh** [comment]
Many thanks!! I'll be sure to send you some app details soon.
