### ISSUE TITLE
Disable Automatic Link Detection

### ISSUE THREAD

**Issue by mRs-** [AliSoftware/OHAttributedLabel#112]
Is it possible to deactivate the automatic link detection? How can i archive this?

**Comment by AliSoftware** [comment]
See the header file, simply set the `automaticallyAddLinksForType` property to none.

For one given instance:

`[attrLabel setAutomaticallyAddLinksForType:0]`

For all instances, you can of course use the standard `UIAppearance` proxy as for any iOS UIKit class:

`[[attrLabel appearance] setAutomaticallyAddLinksForType:0]`
