### ISSUE TITLE
About OHAttributedLabel padding question

### ISSUE THREAD

**Issue by mjspawn** [AliSoftware/OHAttributedLabel#114]
![iOS 2013-1-15 11 23 33 ](https://f.cloud.github.com/assets/3120839/68045/90eabdf2-5f27-11e2-85a4-9baee9ebbbdf.png)
why padding not the same?I use \n to line break and ohLabel.lineBreakMode = NSLineBreakByWordWrapping;
ohLabel.attributedText = [OHASBasicHTMLParser attributedStringByProcessingMarkupInAttributedString:cell.ohLabel.attributedText];

**Comment by mjspawn** [comment]
i figure it out using {.spec = kCTParagraphStyleSpecifierMinimumLineSpacing,.valueSize = sizeof(CGFloat), .value = (const void_)&lineSpacing},
        {.spec = kCTParagraphStyleSpecifierMaximumLineSpacing,.valueSize = sizeof(CGFloat), .value = (const void_)&lineSpacing}

**Comment by AliSoftware** [comment]
**You should use the new `OHParagraphStyle` for that** (that I added in the latest versions), it is a wrapper around `CTParagraphStyle` that is easier to use than the `CTParagraphStyle` C structures. See my demo project, I demonstrate it already.

---

_By the way, to be frank I didn't understand your question as:
1. you talk about padding at first but solve it with line spacing (which is a different font attribute than padding)
2. you didn't annotate your screen capture so I was unable to understand which part of your image you were talking about_
