### ISSUE TITLE
feature request: different links with different colors

### ISSUE THREAD

**Issue by haashem** [AliSoftware/OHAttributedLabel#120]
Hi 
Im using two different links with different behavior. 
for example I want this custom link's color $AttributedLabel$ be blue and this one #AttributedLabel# be orange.

Is this behavior possible with OHAttributedLabel? 
how can I achieve that?

**Comment by haashem** [comment]
this feature is already there: using OHAttributedLabel Delegate

``` objc
- (UIColor *) attributedLabel:(OHAttributedLabel *)attributedLabel colorForLink:(NSTextCheckingResult *)linkInfo underlineStyle:(int32_t *)underlineStyle
{
    if ([[linkInfo.URL scheme] isEqualToString:@"word"]) {
        return attributedLabel.linkColor = [UIColor colorWithRed:125/255.0F green:25/255.0F blue:0 alpha:1 ];
    } else {
        return attributedLabel.linkColor = [UIColor blueColor];
    }
}
```

**Comment by AliSoftware** [comment]
Like you said, just use the delegate method to indicate different colors for different links.
See also issue #113 for more info and tips on how to detect custom markup and generate links with different schemes accordingly, depending on you own needs and custom markup like `$...$` and `#...#`.
