### ISSUE TITLE
-[OHAttributedLabel recomputeLinksInTextIfNeeded] Performance

### ISSUE THREAD

**Issue by xissburg** [AliSoftware/OHAttributedLabel#124]
I am using OHAttributedLabels in table view cells and I noticed it is a bit slow when running in an iPhone 4. I ran a Time Profiler Instrument on it and I can see that the calls to recomputeLinksInTextIfNeeded is taking about 10% of all processing. This method is called even though I am not even using links. Is there something I can do to avoid this method being called? Anyway, I think that this method should be called less frequently and/or it should be optimized.

Thanks.

**Comment by aufflick** [comment]
label.automaticallyAddLinksForType = 0;

**Comment by xissburg** [comment]
Hah, thanks for pointing that out. It seems to be only a little bit faster now. At least it is not anymore wasting time 'computing links' and stuff. 

Thanks!
