### ISSUE TITLE
problem in highlighting multiline custom link which has another custom link

### ISSUE THREAD

**Issue by haashem** [AliSoftware/OHAttributedLabel#125]
I have poems that each part of it is in a single line. (red lines)

1- when I add a custom link for words (as you see here in blue color), poem's custom link won't completely highlighted!

![Screen Shot 2013-02-11 at 8 16 57 PM](https://f.cloud.github.com/assets/3206748/145736/a22a067e-746f-11e2-8ff6-a802a8a797f5.png)
![Screen Shot 2013-02-11 at 9 01 50 PM](https://f.cloud.github.com/assets/3206748/145791/a911db5e-7471-11e2-9338-3987daea8322.png)

 how should I solve it?

linkRunRect in  -(void)drawActiveLinkHighlightForRect:(CGRect)rect
only gives me the bound of a single line! so I have to multiply its height 2 times till the popover appears in the right position!
2- so problem is that after adding a custom link for a word in the poem, when I tap on the first line of poem, the popover won't appears in the right position (because I had to multiply line height 2 times). is there anyway the find the whole bound of multiline poem (red rectangle)?

![Screen Shot 2013-02-11 at 8 21 43 PM](https://f.cloud.github.com/assets/3206748/145760/5a62bbf0-7470-11e2-99f0-5d596ae368ce.png)

![Screen Shot 2013-02-11 at 8 19 23 PM](https://f.cloud.github.com/assets/3206748/145692/68486e74-746e-11e2-96a4-c205b7699694.png)

**Comment by haashem** [comment]
so I checked and saw

self.activeLink = [self linkAtPoint:pt];
 |
 |
 |
\/

 -(NSTextCheckingResult*)linkAtPoint:(CGPoint)point

in OHAttributedLabel implementation, returns different activeLink range, if there is a custom link in a custom link.
and therefore we encounter partial background highlighting.

I couldn't understand how this method is working, 
so still waiting to know how should I solve this problem.

**Comment by AliSoftware** [comment]
I didn't have time to check my code about that, but I am not sure I understand your problem.
You shouldn't have a link inside a link, that's not logical at all.

Imagine you have the text "xxxaaabbbaaaxxx" and adds a link A on the "aaabbbaaa" part. Then of course if you later add another link B on the "bbb" text inside your first link, then you will have 3 different `CTRuns` on your `NSAttributedString` (see `NSAttributedString` (and `CoreText` documentation) about attributes and their ranges, and CTRuns of texts with common attributes if you're not familiar with this), and thus will end up with 3 links (the first "aaa" portion pointing to link A, then the "bbb" portion pointing to link B, and then the last "aaa" portion also pointing to link A), and not one big link and another inside it.

Having "a link inside a link" does not make sense in the "attributed string" vocabulary: a portion of text can't have two "link" attributes so you can't expect your "bbb" portion of your text to be both part of a link pointing to "A" and a link pointing to B at the same time.

**Comment by haashem** [comment]
so, in your opinion how should I handle this task? Is there another way to achieve this?
