### ISSUE TITLE
Character Spacing

### ISSUE THREAD

**Issue by lprhodes** [AliSoftware/OHAttributedLabel#126]
Hi,

Just wondered if there was any way to do character spacing with OHAttributedLabel? 

Thanks!

Luke Rhodes

**Comment by AliSoftware** [comment]
`OHAttributedLabel` uses `NSAttributedString` attributes, and uses Apple's CoreText as its rendering engine.
So anything possible with NSAttributedString attributes and CoreText on iOS is possible here. But note that Apple's implementation of CoreText on iOS does not support all the attributes that it supports on OSX.

The only attribute that could potentially match what you seek may be `NSExpansionAttributeName` (described [here in the NSAttributedString Application Kit Additions Reference](https://developer.apple.com/library/mac/#documentation/Cocoa/Reference/ApplicationKit/Classes/NSAttributedString_AppKitAdditions/Reference/Reference.html#//apple_ref/doc/uid/20000167-BAJJCCFC) in Apple's OSX doc). But I'm not sure that it is exactly what you are looking for, and even if Apple did implement support for it in the iOS version of CoreText. Worth a try anyway.

I can't see any other official attribute to make it possible to change the character spacing manually (except of course changing the text alignment of your NSAttributedString text (or at least one of its paragraph) to `kCTJustifiedTextAlignment`, of course, to make the paragraph justified, but I don't think that's what you're asking)

**Comment by AliSoftware** [comment]
I'm closing this one, see #127 for any following discussion
