### ISSUE TITLE
Link detection uses wrong assumptions about the position of the text frame

### ISSUE THREAD

**Issue by stigi** [AliSoftware/OHAttributedLabel#13]
When `self.centerVertically` or `self.extendBottomToFit` are set the textFrame is drawn with an offset (see `rect` in -`drawTextInRect:`).
This offset isn't taken into account when detecting links at a touched point inside the label.

**Comment by AliSoftware** [comment]
I think the code I used fixes this correctly (I checked in multiple cases, especially with `centerVertically=YES` and links in different positions in the text) but feel free to check my assumptions and code, as I used your helper functions (hopefully correctly?)

**Comment by stigi** [comment]
hey, didn't have time to look at all this this week. just wanted to give a short hello. will look at it the coming week :)

**Comment by AliSoftware** [comment]
Great, thanks :) Let me know
