### ISSUE TITLE
How to get height in heightForRowAtIndexPath

### ISSUE THREAD

**Issue by leeeboo** [AliSoftware/OHAttributedLabel#131]
I use OHAttributedLabel in my uitableviecell. And how to make the lable auto height and also make cell auto height? THX

**Comment by Frizlab** [comment]
You could use for instance

```
[<#your attributed string#> sizeConstrainedToSize:CGSizeMake(<#your attributed label width#>, CGFLOAT_MAX)];
```

**Comment by leeeboo** [comment]
I have try this. but maybe the font is not same as i set in Storyboard. How do i set a font to an attributed string? thx

**Comment by Frizlab** [comment]
Transform your attributed string into a mutable attributed string if it's not already mutable (using `mutableCopy`). Then use the commodity method `setFont:` provided with OHAttributedLabel.
I remember having (or having read some people having) trouble with the `sizeConstrainedToSize:` method however. If your attributed string will contain a string with the same font from the beginning to the end, consider using

```
- (CGSize)sizeWithFont:(UIFont *)font constrainedToSize:(CGSize)size;
```

on a standard `NSString`.

**Comment by leeeboo** [comment]
thx

**Comment by AliSoftware** [comment]
Thanks @Frizlab for providing support for @leeeboo , I unfortunately don't have much time those days to spend on my libs so this help is appreciated ;)

@leeeboo In the Demo project provided on this repo there is a Tab to demonstrate the use of an `OHAttributedLabel` in an `UITableView`, including managing the computation of the height of the `UITableViewCells` depending on the `NSAttributedString` to display, exactly as you needed in your question ;)

**Comment by Frizlab** [comment]
No problem; glad I can help :)
