### ISSUE TITLE
Highlight text color

### ISSUE THREAD

**Issue by ryanmsusa** [AliSoftware/OHAttributedLabel#148]
Is there any way to have a text label 2 colors and also have the highlight color 2 colors.

By highlight color I mean for example when pressing on a tableviewcell

**Comment by AliSoftware** [comment]
You want only one `OHAttributedLabel` with an attributedString composed of multiple colors, or multiple `OHAttributedString` with a different color each?

For the second case, the solution is obvious: configure each instance with the wanted color.

For the first case, it is not currently possible. But we could imagine adding a delegate method that works the same way it does for the linkColors (see lines 240 and 250 of `OHAttributedLabel.m`), using the color returned by the delegate if the delegate method is implemented, and the color in the property if not. Feed free to propose a pull request for that (sorry but I won't have time to add that code myself, but if you do I can easily merge)

**Comment by DZamataev** [comment]
Certainly not `OHAttributedString` but `NSAttributedString`.

**Comment by TamilRaja** [comment]
HI 

  I have change the background colour using singleton class. Any ideas or sample code  (IOS) .
