### ISSUE TITLE
Links can still be activated with automaticallyDetectLinks=NO

### ISSUE THREAD

**Issue by idpaterson** [AliSoftware/OHAttributedLabel#15]
When `automaticallyDetectLinks` is disabled, links are not detected and decorated during the styling phase. However, the link can still be activated. The issue appears to be in `linkAtCharacterIndex:` which does not check the `automaticallyDetectLinks` flag, a simple fix. 

This is particularly problematic in the case where that text is actually part of a custom link that is unrelated to the URL.

**Comment by AliSoftware** [comment]
Thanks, that's fixed.
