### ISSUE TITLE
Can't get multi-line sizeToFit to work

### ISSUE THREAD

**Issue by rscott78** [AliSoftware/OHAttributedLabel#160]
I've been using a UILabel in a view that's been working great for months. I've got to my XIB and changed the class to an OHAttributedLabel and my multi-line logic has suddenly stopped working.

For the UILabel I simply called sizeToFit and it worked the magic, however here that doesn't seem to be the case. I end up with a single line of text with "..."'s at the end.

Is there something special I should do to get it working?

**Comment by AliSoftware** [comment]
Duplicate with #3
