### ISSUE TITLE
adjustsFontSizeToFitWidth

### ISSUE THREAD

**Issue by mosca1337** [AliSoftware/OHAttributedLabel#169]
I am trying to get OHAttributedLabel to automatically scale down the font according to the defined width of my OHAttributedLabel frame. I am looking for a method similar to

```
myLabel.adjustsFontSizeToFitWidth = YES;
```

Any suggestions?

**Comment by AliSoftware** [comment]
Unfortunately, it seems that Apple's CoreText framework does not have any method to do something like this, and as my lib is merely a wrapper around CoreText I can't see any mean to do this properly.

Keep me posted if you find a solution I'd be glad to merge it.
