### ISSUE TITLE
Tappable/Linking  text

### ISSUE THREAD

**Issue by anc1revv** [AliSoftware/OHAttributedLabel#18]
I used the OHAttributedLabel to color different parts of my string.  Although the tapping/linking element of the OHAttributedLabel would be great for future development for my app, I currently do not want this feature.  Is there a way to turn off linking with an OHAttributedLabel?  
 Basically whenever i tap the text, i get an error at link in point.

thanks for any suggestions!

**Comment by AliSoftware** [comment]
Hi,

I don't really understand your question: doesn't the `automaticallyDetectLinks` property of OHAttributedLabel answers your needs?

And what is that error you are talking about that you get at linkAtPoint when you tap the text? (Basically I can't fix this error if I don't know what error it is :-P)
