### ISSUE TITLE
In objective c, how to change text which one selected like "bold","italic","Underline" in textfield 

### ISSUE THREAD

**Issue by honneeyy** [AliSoftware/OHAttributedLabel#189]
![screen shot 2017-06-26 at 12 47 00 pm](https://user-images.githubusercontent.com/8946387/27528464-19e20c00-5a6e-11e7-838a-c10b906cebd1.png)

**Comment by AliSoftware** [comment]
Can you be more explicit? I'm not sure I understand your request?!

**Comment by honneeyy** [comment]
hi,@AliSoftware..my problem is solved..thank you so much
