### ISSUE TITLE
CTFontCreateWithName leaks...

### ISSUE THREAD

**Issue by joshrl** [AliSoftware/OHAttributedLabel#2]
You need to release fonts created with CTFontCreate with CFRelease
For example in:

```
-(void)setFontName:(NSString*)fontName size:(CGFloat)size range:(NSRange)range {
  // kCTFontAttributeName
  CTFontRef aFont = CTFontCreateWithName((CFStringRef)fontName, size, NULL);
  [self addAttribute:(NSString*)kCTFontAttributeName value:(id)aFont range:range];
}
```

**Comment by AliSoftware** [comment]
Of course you're right, I don't understand why I didn't release them !
Thanks I'll fix this asap !

**Comment by AliSoftware** [comment]
I just pushed a FIX if you're interested.

There is also a feature that I wanted to add to this class, I just opened an issue about it (but unfortunately, I don't have much time those days to implement it)
