### ISSUE TITLE
Crash on tap

### ISSUE THREAD

**Issue by gon** [AliSoftware/OHAttributedLabel#21]
Hi!

I'm getting crashes every time a user taps onto a OHAttributedLabel whether it contains links, several fonts or nothing special. Links do work properly though and don't make the app crash.

```
// Add the title label.
OHAttributedLabel *titleLabel = [[OHAttributedLabel alloc] initWithFrame:CGRectMake(0, 0, 200, 3)];
NSString* titleText = [dictionary objectForKey:SERVER_API_ACTIVITY_UPDATE_TITLE_KEY];
NSMutableAttributedString* attributedTitleText = [NSMutableAttributedString attributedStringWithString:titleText];
[attributedTitleText setFont:[UIFont fontWithName:@"Helvetica" size:13]];
[attributedTitleText setFont:[UIFont fontWithName:@"Helvetica-Bold" size:13] range:[titleText rangeOfString:[dictionary objectForKey:SERVER_API_ACTIVITY_UPDATE_USER_KEY]]];
[titleLabel addCustomLink:[NSURL URLWithString:@"http://www.foodreporter.net/dish/list"] inRange:[titleText rangeOfString:@"thread"]];
[attributedTitleText setTextColor:[UIColor blackColor]];
titleLabel.attributedText = attributedTitleText;
titleLabel.numberOfLines = 2;
titleLabel.lineBreakMode = UILineBreakModeWordWrap;
[view addSubview:titleLabel];
[titleLabel release];
```

When I tap on anything in the OHAttributedLabel except on the link, I get this error and crash:
`warning: Unable to read symbols for /Developer/Platforms/iPhoneOS.platform/DeviceSupport/4.2.1 (8C148)/Symbols/Developer/usr/lib/libXcodeDebuggerSupport.dylib (file not found).`

OHAttributedLabel.m line 264 in the linkAtPoint method:
`CFIndex nbLines = CFArrayGetCount(lines);   >> Program received signal: "EXEC_BAD_ACCESS".`

Any direction on how to fix this?

Gon
ps: I love the way this library works with a range! Super handy.

**Comment by AliSoftware** [comment]
Hi @gon

Thanks for your interest in OHAttributedLabel.
I tried your code in my "AttributedLabel Example" project (provided in this repo too) but didn't get any crash.

Are you sure you are using the last version and you did pull recently ? There have been multiple changes in the `linkAtPoint` code recentrly.

Please let me know.

**Comment by gon** [comment]
Hi Ali, thanks for the ping(s) back!

I just found your project, cloned May 25 :-) so that shouldn't be it. I asked some help with this to @kevinchartier who fixed it like so: Add the following code to the linkAtPoint: method, on the line before the line that crashes:

```
if (!lines) {
   return nil;
}
```

The section of code becomes:

```
CFArrayRef lines = CTFrameGetLines(textFrame);
if (!lines) {
   return nil;
}
CFIndex nbLines = CFArrayGetCount(lines);
NSTextCheckingResult* link = nil;
```

**Comment by ketanmori** [comment]
hi 
i have downloaded this files and libOHAttributedLabel.a files are missing !!!!!
so that i got an error " libOHAttributedLabel.h " not found.

**Comment by AliSoftware** [comment]
Hi @ketanmori 
1. I don't understand what files you are talking about and why you are posting your question in this particular issue, in what is it related?
2. There is no pre-compiled `libOHAttributedLabel.a` file provided in the GitHub repository, you have to compile it using the provided project. Every step is explained in details both in the README file and in the dedicated  Wiki pages. _Basically adding this project to your workspace is the same procedure as the one quite every third-party projects uses out there, nothing new here._
3. There is no `"libOHAttributedLabel.h"` file whatsoever. The header name is `OHAttributedLabel.h` not `libOHAttributedLabel.h`. Once again, follow the instructions provided in the README where everything is explained step by step.
