### ISSUE TITLE
sizeThatFits bug

### ISSUE THREAD

**Issue by EricShapiro** [AliSoftware/OHAttributedLabel#23]
The last line of sizeThatFits has a typo:

Current:
return CGSizeMake(sz.height,sz.height+1); // take 1pt of margin for security

Should be:

return CGSizeMake(sz.width,sz.height+1); // take 1pt of margin for security

**Comment by AliSoftware** [comment]
Nice catch ;) Fixed inline.

**Comment by EricShapiro** [comment]
I changed my local version to ignore the size parameter too and to use CGSizeMake(CGFLOAT_MAX,CGFLOAT_MAX) rather than CGSizeMake(w,CGFLOAT_MAX) in the call to CTFramesetterSuggestFrameSizeWithConstraints(). 

I'm not 100% sure that's the right solution for everyone, but in my case the label shrinks and grows to whatever size it needs and I don't want the width constrained.

**Comment by AliSoftware** [comment]
Yes, my original version did not change the width of the label and only changed the height.
It disturbed some users, so the solution I now use is the more standard one I found :
- `sizeThatFits:(CGSize)sz` return the **real CGSize that fits the text**, with its width **never** growing (possibly smaller than the original size, if the text is shorter for example, but never greater that this original size anyway) and only the height that adjusts.
  _(Note: This differs from Apple's UILabel sizeThatFits implementation, which tends to fit its text on one line, which I found particularly annoying)_
- If you need custom sizing constraints, retrieve the CGSize in a local variable and adapt it to your needs before changing the size on your own (thus you do not call sizeToFit but compute it yourself). This is actually quite straightforward.

Example:

```
CGRect r = self.bounds;
CGSize sz = [self sizeThatFits:r.size];
// adapt to your needs, here I constraint the width to avoid the label to shrink
r.size = CGSizeMake(r.size.width, sz.height); 
self.bounds = r;
```

With this solution, I think everyone can find the solution s/he needs depending on its context.
