### ISSUE TITLE
Does Not want the link to open in Safari…

### ISSUE THREAD

**Issue by rahul11Victory** [AliSoftware/OHAttributedLabel#26]
Hi Ali,
I have used OHAttributedLabel and it is working well.
But the problem is when i click,the link opens with Safari. I want it to be opened using a web view (Created already). 
So can you tell me where should i suppose to make changes to do that?

Thanks,
Rahul

**Comment by AliSoftware** [comment]
Hi Rahul,

No change needed in my class, this is already handled.

You just need to implement the optional delegate method shouldFollowLink: to do whatever you want in it (in your case show the URL in your webview) and return NO (to prevent the default behavior that would open the link in Safari)

Olivier

---

Envoyé de mon iPhone ;-)

**Comment by rahul11Victory** [comment]
Hi Ali,

I have founded that method but not able to work it out.
What i have done is 
Added OHAttributedLabel files in my classes folder.

in Interface Part:

@interface Organizer :ViewController<OHAttributedLabelDelegate> 

In Organizer i am using a TableView in the rows of the table view i have implemented OHAttributedLabel.

and i have added the method like this in implementation of Organizer like

-(BOOL)attributedLabel:(OHAttributedLabel_)attributedLabel shouldFollowLink:(NSTextCheckingResult_)linkInfo{
    NSLog(@"Link Info:%@",linkInfo);
    return NO;
}

but when i click the link it still opens in Safari n there is no NsLog Printed on console.

Can you guide me what should i do to make it happen…?? (Provided that i am new to iphone and don't know much about delegate method implementation)

Help will be appreciated….

Thanks,
Rahul

**Comment by rahul11Victory** [comment]
And another problem is i am not able to click the OHAttributedLabel created in the Cell of TableView...??
why So..???

**Comment by AliSoftware** [comment]
That's basic iPhone dev really, consider reading the Apple documentation to learn about delegates, this design pattern is use quite everywhere in the Cocoa framework so it's worth taking some time to learn about it.

What you probably forgot in your case is to define which object is the delegate of your OHAttributedLabel objects (yourAttrLabel.delegate = self, probably, if you implement the delegate method in the same class that you create your label into)

Olivier

---

Envoyé de mon iPhone ;-)

**Comment by rahul11Victory** [comment]
Bingo...!!! 

Thanks Buddy it did worked... I have missed the Setting delegate part...
But still i am not able to click the Label in Cell of the table view.

**Comment by AliSoftware** [comment]
Does work for me, using it every day in custom tabkeviewcells no reason not to catch the tap on the label (except if you set userInteractionEnabled to false, of course)

Olivier

---

Envoyé de mon iPhone ;-)
