### ISSUE TITLE
Sub-pixel size from sizeThatFits causing blurriness

### ISSUE THREAD

**Issue by joethephish** [AliSoftware/OHAttributedLabel#28]
I was finding that when using small point sizes, and making use of sizeThatFits, fonts were looking blurry.

I tracked it down to the fact that it was calculating bounds that had sizes on sub-pixel boundaries. I'm guessing that due to the fact that it flips the rendering vertically, this was causing the text rendering to draw at a sub-pixel coordinate.

My fix is to change the last line of sizeThaFits to:

```
return CGSizeMake(floorf(sz.width),floorf(sz.height+1));
```

Does seem like a sensible fix?

**Comment by AliSoftware** [comment]
Yeah it seems great :)

Never tried nor experienced this issue myself, but I guess this is ok to floor the returned size as you suggest.
Just included this in the latest commit (with additional +1 margin also for the width too)
