### ISSUE TITLE
Error in dealloc

### ISSUE THREAD

**Issue by ashfurrow** [AliSoftware/OHAttributedLabel#29]
In xOS 5 beta, dealloc has an error that crashes the app. We release textFrame and then call [super dealloc], which must call [self setNeedsDisplay], which calls [self resetTextFrame], which releases the textFrame again.

It's easily fixed by changing this 
    if (textFrame) CFRelease(textFrame);
to this
    if (textFrame) 
    {
        CFRelease(textFrame);
        textFrame = NULL;
    }
In dealloc.

**Comment by AliSoftware** [comment]
Actually this was already fix via the recent pull request #27

But I didn't know that this was new to iOS5 (as I didn't have enough time to test iOS5 yet and thus didn't have the issue so far), so thanks for the explanation :)
