### ISSUE TITLE
Phone Number Links

### ISSUE THREAD

**Issue by ghost** [AliSoftware/OHAttributedLabel#32]
In addition to standard URLs, I had a need for auto-detecting phone number links on devices that support calling.  I decided to add it in as an optional addition to auto-detecting URLs, for easy customization:

In OHAttributedLabel.h I added two properties:

``` objective-c
@property(nonatomic, assign) BOOL automaticallyDetectURLLinks; //!< Defaults to YES, only takes effect if automaticallyDetectLinks is YES
@property(nonatomic, assign) BOOL automaticallyDetectPhoneLinks; //!< Defaults to YES if device can make phone calls (i.e, iPhone), NO otherwise (i.e., iPad); only takes effect if automaticallyDetectLinks is YES
```

Then in OHAttributedLabel.m I added an internal method to return the types of links that should be auto-detected:

``` objective-c
-(NSTextCheckingTypes)autoDetectLinkTypes
{
    NSTextCheckingTypes linkTypes = 0;
    if (self.automaticallyDetectURLLinks)
        linkTypes = linkTypes | NSTextCheckingTypeLink;
    if (self.automaticallyDetectPhoneLinks)
        linkTypes = linkTypes | NSTextCheckingTypePhoneNumber;
    return linkTypes;
}
```

This is used in both `attributedTextWithLinks` and `linkAtCharacterIndex` when creating the NSDataDetector.  And then when the touch ends we need to do the proper action:

``` objective-c
    if (activeLink.resultType == NSTextCheckingTypeLink)
    {   
        // we can check on equality of the links themselfes since the data detectors create new results
        if (activeLink.URL && [activeLink.URL isEqual:linkAtTouchesEnded.URL]) {
            BOOL openLink = (delegate && [delegate respondsToSelector:@selector(attributedLabel:shouldFollowLink:)])
            ? [delegate attributedLabel:self shouldFollowLink:activeLink] : YES;
            if (openLink) [[UIApplication sharedApplication] openURL:activeLink.URL];
        }
    }
    else if (activeLink.resultType == NSTextCheckingTypePhoneNumber)
    {
        // we can check on equality of the links themselfes since the data detectors create new results
        if (activeLink.phoneNumber && [activeLink.phoneNumber isEqualToString:linkAtTouchesEnded.phoneNumber]) {
            BOOL openLink = (delegate && [delegate respondsToSelector:@selector(attributedLabel:shouldFollowLink:)])
            ? [delegate attributedLabel:self shouldFollowLink:activeLink] : YES;
            if (openLink) [[UIApplication sharedApplication] openURL:[NSURL URLWithString:[NSString stringWithFormat:@"tel:%@", activeLink.phoneNumber]]];
        }
    }
```

Finally, we should have an intelligent initialization in `commonInit`:

``` objective-c
    automaticallyDetectLinks = YES;
    automaticallyDetectURLLinks = YES;
    automaticallyDetectPhoneLinks = [[UIApplication sharedApplication] canOpenURL:[NSURL URLWithString:@"tel:555-555-5555"]];
```

I haven't extensively tested this addition, but it seems to work well for my immediate needs.

**Comment by AliSoftware** [comment]
Great addition, seems very nice, thanks :-) I think I'll integrate it in a future version !

Did you do a fork on my project in your github? If so, you make a "Pull Request" so that I merge your modifications into my github repo. If you didn't, don't bother, I'll apply your code you quoted above myself in the next commit :)

Thanks!

**Comment by AliSoftware** [comment]
Added in last commit 08de91ddcb7bd11b1d27af874764fc8eb9904155
I preferred changing the property `automaticallyDetectLinks` to `automaticallyAddLinksForType` so that you can activate whatever link types (including links, phone numbers, but also addresses or dates)
