### ISSUE TITLE
UILineBreakModeTailTruncation doesn't work properly when resize

### ISSUE THREAD

**Issue by athanhcong** [AliSoftware/OHAttributedLabel#36]
OHAttributedLabel does not add (...) mark at the end when some of my text if truncated.

I created an OHAttributedLabel, set UILineBreakModeTailTruncation, put an attributed string.
When I change the label frame, bug found: I do not see an (...) mark at the end of the label.

Anyone suggest sth that can fix this?

**Comment by AliSoftware** [comment]
Duplicate with #3, so closing this one (continue discussion on #3)

Would really appreciate any suggestion to solve this in CoreText anyway (as it does not seems to be supported by standard CoreText layout methods?)
