### ISSUE TITLE
label click

### ISSUE THREAD

**Issue by saimayaqub** [AliSoftware/OHAttributedLabel#38]
Hi,

Is there any way that i can make my label text clickable without affecting its formatting?  On click of the label, I want to navigate to another view, but the formatting of my text should remain same as i set in attributed string. 

Please help me out.

Thanks
Salman

**Comment by AliSoftware** [comment]
Hi,

I thought the `@property` and their doc in the header were self-explanitory?
- If you need your links not to have their color changed, just set the `linkColor` property to `nil`.
- If you need your links not to be underlined, just set the `underlineLinks` property to `nil`.

If you need finer control over this, you can also use the `colorForLink: underlineStyle:` delegate method which obey the same rules (returning a nil color from there does not modify the color of your text, setting a style to 0 does not modify the underlining either)
