### ISSUE TITLE
Memory Leak occurring when setting text alignment

### ISSUE THREAD

**Issue by NathanIsHere** [AliSoftware/OHAttributedLabel#40]
When applying a Text Alignment value against an OHAttributedLabel, I am finding that I am getting small memory leaks for each time I am setting it. In some views, I am setting it for six or seven separate labels, meaning the number of leaks corresponds equally to the number of OHAttributedLabels.

Running instruments, I see that the leak traces back to the method:

'''
-(void)setTextAlignment:(CTTextAlignment)alignment lineBreakMode:(CTLineBreakMode)lineBreakMode range:(NSRange)range {
    // kCTParagraphStyleAttributeName > kCTParagraphStyleSpecifierAlignment
    CTParagraphStyleSetting paraStyles[2] = {
        {.spec = kCTParagraphStyleSpecifierAlignment, .valueSize = sizeof(CTTextAlignment), .value = (const void_)&alignment},
        {.spec = kCTParagraphStyleSpecifierLineBreakMode, .valueSize = sizeof(CTLineBreakMode), .value = (const void_)&lineBreakMode},
    };
    CTParagraphStyleRef aStyle = CTParagraphStyleCreate(paraStyles, 2);
    [self addAttribute:(NSString*)kCTParagraphStyleAttributeName value:(id)aStyle range:range];
    CFRelease(aStyle);
}
'''

found in NSAttributedString+Attributes.m. 

Using Instruments, I am tracing this leak to line 153 of this file. 

This line reads as CTParagraphStyleRef aStyle = CTParagraphStyleCreate(paraStyles, 2)

Below is a snippet of my code, where I set the alignment to justify for the field. I've only been playing with this module of code for a day, so I can accept that there is something I am doing wrong on my side.

```
NSMutableAttributedString   *attrStr                = [NSMutableAttributedString attributedStringWithString:speil_body];                    
OHAttributedLabel *speil_paragraph  = [[OHAttributedLabel alloc] init];
speil_paragraph.attributedText      = attrStr;
speil_paragraph.font                = [UIFont systemFontOfSize:SPEIL_FONT_SIZE];
speil_paragraph.backgroundColor     = [UIColor clearColor];
speil_paragraph.lineBreakMode       = UILineBreakModeWordWrap;
speil_paragraph.textAlignment       = UITextAlignmentJustify;
```

I will add more to this report, as I investigate further

**Comment by NathanIsHere** [comment]
hey

My apologies for raising this issue. Seems that this has been addressed in an earlier issue (see https://github.com/AliSoftware/OHAttributedLabel/issues/5). Basically, when the code was revised and this 'Apple Workaround' applied to most of the methods in NSAttributedString+Attributes.m, it was not applied to the below method:

'''
-(void)setTextAlignment:(CTTextAlignment)alignment lineBreakMode:(CTLineBreakMode)lineBreakMode range:(NSRange)range {
    // kCTParagraphStyleAttributeName > kCTParagraphStyleSpecifierAlignment
    CTParagraphStyleSetting paraStyles[2] = {
        {.spec = kCTParagraphStyleSpecifierAlignment, .valueSize = sizeof(CTTextAlignment), .value = (const void_)&alignment},
        {.spec = kCTParagraphStyleSpecifierLineBreakMode, .valueSize = sizeof(CTLineBreakMode), .value = (const void_)&lineBreakMode},
    };
    CTParagraphStyleRef aStyle = CTParagraphStyleCreate(paraStyles, 2);
    [self removeAttribute:(NSString_)kCTParagraphStyleAttributeName range:range]; // Work around for Apple leak
    [self addAttribute:(NSString_)kCTParagraphStyleAttributeName value:(id)aStyle range:range];
    CFRelease(aStyle);
}
'''

As soon as I submitted it, I found what I needed. Apologies for raising a past issue.

**Comment by AliSoftware** [comment]
Hi Nathan

Thanks for your report.

No apologies needed here: even if you may have posted in issue #5, this leak is still an issue. So even if it's due to Apple in NSAttributedString , we still need to insert a workaround here anyway to get around this leak and as I forgot to insert it in this method I still should add the workaround here too in a future commit to fix this.

Thanks!

**Comment by AliSoftware** [comment]
Fixed :)
