### ISSUE TITLE
too tall font disappears

### ISSUE THREAD

**Issue by kevinlawler** [AliSoftware/OHAttributedLabel#46]
It seems that if the font size of `attributedText` is too large (the font height exceeds the height of the frame) the text fails to display at all. This was unexpected. I assumed too large text would display at least partially. The text disappears even if `clipsToBounds` is  set to `NO`.

Please ignore if this is a feature or if I have spent too little time understanding how it works.

**Comment by AliSoftware** [comment]
Duplicate with #42 : That's how CoreText manages its rendering.

To render the last line even if there is not enough space for the whole line to be rendered, we need to manually reimplement completely the framing process that is today done automatically by CTFrameSetter
