### ISSUE TITLE
Using OHAttributedLabel inside a UITableViewCell will cause scrolling not smooth

### ISSUE THREAD

**Issue by alanchen** [AliSoftware/OHAttributedLabel#54]
Hi,

I am using OHAttributedLabel inside a UITableViewCell like this :

// *********************
CustomTableViewCell _cell = [tableView dequeueReusableCellWithIdentifier:cellIdentifier];
if(cell==nil)
{
  cell=[[CustomTableViewCell  alloc] initWithStyle:UITableViewCellStyleDefault reuseIdentifier:cellIdentifier];
}
cell.attributedLabel.attributedText=[NSAttributedString attributedStringWithString:@"test"];
// *_***********************
but  It will make UITableView scroll not smooth.

Do I miss something or using OHAttributedLabel in wrong way ?

Please help me out.

Thanks a lot.
Alan

**Comment by AliSoftware** [comment]
Hi,

I (and a lot of other people using my class) also use it in an
UITableViewCell exactly the same way without any problem or performance
issue.

But I guess that you probably don't use the reuse mechanism of
UITableViewCells correctly. You really have to use it to make your
tableview scrolling smoothly (and that's not related to OHAttributedLabel,
even if allocating a cell each time during scrolling -- as you will do if
not using the standard reuse mechanism of UITableViewCells -- will always
slow down the scrolling but may slow it even more due to CoreText
usage/allocations, whereas using the reuse mechanism -- as you always
should do for every UITableViews in general -- will avoid this performance
issue)

On Wed, Dec 14, 2011 at 5:01 AM, alanchen <
reply@reply.github.com

**Comment by emanuelef** [comment]
I'm using it inside a Table View, taking advantage of reusing and it's ok.
It slowed down a bit on my old iPhone 3G, needs to check on newer devices.
I do a removeAllCustomLinks when reusing the cell, to then set new links with addCustomLink.
Both performs a setNeedsDisplay, in my case I just need one. But not sure it would really improve much.

**Comment by AliSoftware** [comment]
Drawing an `NSAttributedString` using CoreText is obviously slower than drawing a plain string using UIKit.

Anyway, the drawing should be quite optimized in the last version of this class. Obviously, CoreText is slower on 3G iPhones, but smooth on my 3GS (and of course on my 4GS too).
- In the last version, there is no need to call removeAllCustomLinks when reusing the `NSAttributedString` as it is called automatically when you change the value of `attributedText` property
- Calling `setNeedsDisplay` multiple times (in the same run loop iteration) doesn't change anything nor affect the performance. `setNeedsDisplay` simply sets a flag on the `UIView` to tell the composition & drawing loop to redraw the `UIView` on the next drawing loop iteration.

_(See the associated Programming Guide about custom UIViews for more info on all this)_

**Comment by mcohnen** [comment]
I'm seeing the same behavior here. I have a custom cell which scrolls perfect in my iphone 4s. It has images (which I'm properly caching and loading in the bg), some buttons, and a UILabel. Simply changing the UILabel to be OHAttributedLabel makes the scroll sticky. I'm talking about scrolling REALLY fast in a table with hundreds of rows. Again, using a UILabel makes the scroll perfect, or not setting attributedString at all (setting it to nil). So my guess is that the drawing is actually slow. 

I'm testing drawing just an attributed string with text @"test", no fancy stuff. I'm a bit of a smooth scrolling paranoid, but there is really a big difference here.

Thanks

**Comment by jparise** [comment]
You might try my proposed changes in #60.  They were motivated by poor table scrolling performance.

**Comment by mcohnen** [comment]
Thanks for the suggestion. I moved to TTStyledTextLabel instead. It is not a UILabel subclass, but is really fast and managed to get it working the way I wanted. 

Good to know somebody else was having these issues, as by the comments above, it looked like there was not a problem.

**Comment by AliSoftware** [comment]
Last version 1.3.0 should have improved drawing performance

**Comment by kn-neeraj** [comment]
How about caching of attributed strings?
