### ISSUE TITLE
Customize internalLink style

### ISSUE THREAD

**Issue by emanuelef** [AliSoftware/OHAttributedLabel#58]
Hi,
I'm trying to have internal Link like the one in the example styled differently than regular http links.
But if I do [attrStr setTextColor:[UIColor redColor] range:[txt rangeOfString:@TXT_LINK]]
The color for the link and style is always the regular underlined blue.
Is it possible to style some link (internal in my case) differently?
Thanks

**Comment by AliSoftware** [comment]
Of course.

If you want to change the color used for all links in one `OHAttributedLabel` simply change the `linkColor` property of the `OHAttributedLabel`.

If you want some links to have a different color than other and customize the color of some links, simply implement the `-(UIColor*)colorForLink:(NSTextCheckingResult*)linkInfo underlineStyle:(int32_t*)underlineStyle` delegate method.

**Comment by emanuelef** [comment]
thanks, great library!

**Comment by reejosamuel** [comment]
Hi, is it possible to make the links alone bold also?

**Comment by AliSoftware** [comment]
@reejosamuel Just added this in my latest commit (e5adbffe7f - version [3.1.0](https://github.com/AliSoftware/OHAttributedLabel/wiki/Revisions-History))

Sorry for the delay ;)

**Comment by reejosamuel** [comment]
Thanks, you can close this now
