### ISSUE TITLE
i got 26 apple mach-o linker error

### ISSUE THREAD

**Issue by gn1749465** [AliSoftware/OHAttributedLabel#63]
NSAttributedString+Attributes.h and .m
OHAttributedLabel.h and .m    were added.
after that, the CoreText framework is added.
when I try to build the project
these error is shown

Undefined symbols for architecture armv7:
  "_kCTFontFamilyNameAttribute", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontFamily:size:bold:italic:range:] in NSAttributedString+Attributes.o
  "_CTFrameDraw", referenced from:
      -[OHAttributedLabel drawTextInRect:] in OHAttributedLabel.o
  "_CTFontCreateWithFontDescriptor", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontFamily:size:bold:italic:range:] in NSAttributedString+Attributes.o
  "_CTLineGetStringRange", referenced from:
      _CTLineContainsCharactersFromStringRange in OHAttributedLabel.o
  "_CTLineGetTypographicBounds", referenced from:
      _CTLineGetTypographicBoundsAsRect in OHAttributedLabel.o
     (maybe you meant: _CTLineGetTypographicBoundsAsRect)
  "_CTRunGetTypographicBounds", referenced from:
      _CTRunGetTypographicBoundsAsRect in OHAttributedLabel.o
     (maybe you meant: _CTRunGetTypographicBoundsAsRect)
  "_kCTFontTraitsAttribute", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontFamily:size:bold:italic:range:] in NSAttributedString+Attributes.o
  "_CTRunGetStringRange", referenced from:
      _CTRunGetTypographicBoundsAsRect in OHAttributedLabel.o
      _CTRunContainsCharactersFromStringRange in OHAttributedLabel.o
  "_CTFontCopyFullName", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setTextBold:range:] in NSAttributedString+Attributes.o
  "_CTLineGetOffsetForStringIndex", referenced from:
      _CTRunGetTypographicBoundsAsRect in OHAttributedLabel.o
  "_kCTUnderlineStyleAttributeName", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setTextUnderlineStyle:range:] in NSAttributedString+Attributes.o
  "_CTFontCreateCopyWithSymbolicTraits", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setTextBold:range:] in NSAttributedString+Attributes.o
  "_CTLineGetGlyphRuns", referenced from:
      -[OHAttributedLabel drawActiveLinkHighlightForRect:] in OHAttributedLabel.o
  "_CTFrameGetLines", referenced from:
      -[OHAttributedLabel linkAtPoint:] in OHAttributedLabel.o
      -[OHAttributedLabel drawActiveLinkHighlightForRect:] in OHAttributedLabel.o
  "_kCTFontSymbolicTrait", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontFamily:size:bold:italic:range:] in NSAttributedString+Attributes.o
  "_CTFramesetterCreateWithAttributedString", referenced from:
      -[NSAttributedString(OHCommodityConstructors) sizeConstrainedToSize:fitRange:] in NSAttributedString+Attributes.o
      -[OHAttributedLabel drawTextInRect:] in OHAttributedLabel.o
  "_CTFrameGetLineOrigins", referenced from:
      -[OHAttributedLabel linkAtPoint:] in OHAttributedLabel.o
      -[OHAttributedLabel drawActiveLinkHighlightForRect:] in OHAttributedLabel.o
  "_CTParagraphStyleCreate", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setTextAlignment:lineBreakMode:range:] in NSAttributedString+Attributes.o
  "_kCTParagraphStyleAttributeName", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setTextAlignment:lineBreakMode:range:] in NSAttributedString+Attributes.o
  "_CTFontCreateWithName", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontName:size:range:] in NSAttributedString+Attributes.o
  "_CTFramesetterCreateFrame", referenced from:
      -[OHAttributedLabel drawTextInRect:] in OHAttributedLabel.o
  "_CTFontDescriptorCreateWithAttributes", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontFamily:size:bold:italic:range:] in NSAttributedString+Attributes.o
  "_kCTFontAttributeName", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontName:size:range:] in NSAttributedString+Attributes.o
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setFontFamily:size:bold:italic:range:] in NSAttributedString+Attributes.o
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setTextBold:range:] in NSAttributedString+Attributes.o
  "_CTLineGetStringIndexForPosition", referenced from:
      -[OHAttributedLabel linkAtPoint:] in OHAttributedLabel.o
  "_CTFramesetterSuggestFrameSizeWithConstraints", referenced from:
      -[NSAttributedString(OHCommodityConstructors) sizeConstrainedToSize:fitRange:] in NSAttributedString+Attributes.o
      -[OHAttributedLabel drawTextInRect:] in OHAttributedLabel.o
  "_kCTForegroundColorAttributeName", referenced from:
      -[NSMutableAttributedString(OHCommodityStyleModifiers) setTextColor:range:] in NSAttributedString+Attributes.o
ld: symbol(s) not found for architecture armv7
collect2: ld returned 1 exit status

please help me :(

**Comment by jparise** [comment]
You need to add `CoreText.framework` to your project.

**Comment by pepotiger** [comment]
When you add the files to your project make sure that you add check mark beside "Copy items......" and also make sure sure you put check mark beside the name of your application's targets.

and as jparise said also make sure to import CoreText.framework

**Comment by gn1749465** [comment]
thank you so much!
