### ISSUE TITLE
Automatically increasing label height depending on content

### ISSUE THREAD

**Issue by sarperdag** [AliSoftware/OHAttributedLabel#64]
Is this possible? I don't want my OHAttributedLabels to have a fixed height and try to fit content inside by making the fonts smaller.

**Comment by AliSoftware** [comment]
Yes, simply use `sizeToFit` or `sizeThatFits:` methods of `OHAttributedLabel` as you would do with any other UIView.
These methods are overridden in `OHAttributedLabel` to size the label accordingly.

You can also use the `-(CGSize)sizeConstrainedToSize:(CGSize)maxSize;` method of my `NSAttributtedString+Attributes` category to know the `CGSize` of the NSAttributedString and resize your `OHAttributedLabel` manually accordingly.

**Comment by sarperdag** [comment]
```
    statusDescriptionLabel.delegate = self;
    NSMutableAttributedString* attrStr = [NSMutableAttributedString attributedStringWithString:@"some long text"];
    [attrStr setFont:[UIFont fontWithName:@"Helvetica" size:14]];
    statusDescriptionLabel.attributedText = attrStr;
    statusDescriptionLabel.numberOfLines = 0;
    statusDescriptionLabel.lineBreakMode = UILineBreakModeWordWrap;
    [statusDescriptionLabel sizeToFit];
```

doesn't solve my problem. What am I missing?

**Comment by sarperdag** [comment]
any ideas?

**Comment by AliSoftware** [comment]
What CGSize does the `sizeThatFits:` method returns ?
