### ISSUE TITLE
AutomaticallyAddLinksForType adds incorrect link

### ISSUE THREAD

**Issue by ngoan** [AliSoftware/OHAttributedLabel#67]
I have my OHAttributedLabel auto add link for type set to: NSTextCheckingTypeLink, and in my shouldFollowLink method I am confirming that my label's text is: 

SO SYMMETRICAL “@cassini_: I just made this 47-piece, 562,892-point shape in #PolymerApp http://twitter.com/cassini_/status/196499162097922049/photo/1”

Yet, the label displays the link as: 

http://twitter.com/cassini_/status/196499162097922049/photo/1” [With the extra quotation appended to the end]

Printing out the link I get: 

<NSLinkCheckingResult: 0x1343b240>{89, 62}{http://twitter.com/cassini_/status/196499162097922049/photo/1%E2%80%9D}

.. but it should just be:
http://twitter.com/cassini_/status/196499162097922049/photo/1

Please let me know if I'm doing something wrong or if this is an issue, thanks.

**Comment by AliSoftware** [comment]
Hi

This is not really an issue : Apple's NSDataDetector (that OHAttributedLabel uses to auto-detect links) can't know if the quote is part of the URL (which could be the case, it would be a totally valid URL according to the RFC standard) or not. It considers that once it has detected the start of a link, this link stops at the first character that is invalid for an URL (often a space character)

If you write this very same text in an email for example, the quote character will also be considered as part of the URL too. To make sure the quote is not considered as part of the URL you will have to insert a space between the end of the link and the quote. AFAIK Apple's NSDataDetector does not have such option to ignore specifically some characters and bypass the standard.
