### ISSUE TITLE
Please add semantic version tags.

### ISSUE THREAD

**Issue by stigi** [AliSoftware/OHAttributedLabel#68]
I just created a [pull request](https://github.com/CocoaPods/Specs/pull/176) adding `OHAttributedLabel` to the [CocoaPods](https://github.com/CocoaPods/CocoaPods) package manager repo.

CocoaPods is a tool for managing dependencies for OSX and iOS Xcode projects and provides a central repository for iOS/OSX libraries. This makes adding libraries to a project and updating them extremely easy and it will help users to resolve dependencies of the libraries they use.

However, `OHAttributedLabel` doesn't have any version tags. I’ve added the current HEAD as version `0.0.1.prerelease.1`, but a version tag will make dependency resolution much easier.

[Semantic version](http://semver.org) tags (instead of plain commit hashes/revisions) allow for [resolution of cross-dependencies](https://github.com/CocoaPods/Specs/wiki/Cross-dependencies-resolution-example).

In case you didn’t know this yet; you can tag the current HEAD as, for instance, version 1.0.0, like so:

```
$ git tag -a 1.0.0 -m "Tag release 1.0.0"
$ git push --tags
```

**Comment by AliSoftware** [comment]
Tagged as version 1.2.0 today
(you could consider version 1.0.0 was first version with public API and 1.1.0 was when introduced ARC, 1.2.0 is when API added accessors for NSAttributedString properties, but I failed to push those internal tags in github)
