### ISSUE TITLE
is possible to use html strikethrough tag

### ISSUE THREAD

**Issue by shinrenpan** [AliSoftware/OHAttributedLabel#70]

**Comment by AliSoftware** [comment]
OHAttributedLabel uses NSAttributedStrings (and not HTML). And it uses CoreText to draw those strings.

So you can use all the standard attributes supported by CoreText (see [here](https://developer.apple.com/library/ios/#documentation/Carbon/Reference/CoreText_StringAttributes_Ref/Reference/reference.html)).

AFAIK, the "strikethrough" style is not a standard attribute and is not supported by CoreText.
