### ISSUE TITLE
Xcode 4.4 (4F250): Error "Case value not in enumerated type 'UITextAlignment'"

### ISSUE THREAD

**Issue by jdandrea** [AliSoftware/OHAttributedLabel#71]
See line 59 of OHAttributedLabel.m. No longer able to compile.

Possible workaround: switch ((int)alignment) ... (ehhh, I know, that looks a bit shady, but see what you think).

Please advise - thanks!

**Comment by AliSoftware** [comment]
Yes, Xcode 4.4 introduces a new version of the LLVM compiler which treats enum quite differently (actually they are kind of typed, see the WWDC'12 video sessions #405 and #413.
As I introduced a "fake" new value to the UITextAlignment enum using a #define, the LLVM compiler complains.

I haven't switched to Xcode 4.4 yet, but here are 2 suggestions :
- cast the alignment value to an int, as you suggest. I agree that's a bit shady but it should work anyway
- try using #pragma clang diagnostic ignored "-Wconversion" or "-Wswitch" (#pragma push before  and pop after of course) to bypass the warning (actually quite more shady than the previous suggestion isn't it?)

I guess the casting to an int is the most efficient way to do this, as I can't imagine a way to "extend" the possible values of the UITextAlignment enum for my class only or change the textAlignment's property type to a new enum that adds that value or whatever…

**Comment by jdandrea** [comment]
Hey, I remember sitting in those sessions! :)

Extending would be terrific, if it were possible. Ahh well, whaddaya gonna do. I agree, I think (int) will have to do. Fair enough!

**Comment by AliSoftware** [comment]
Just to let you know, my latest commits changed this a bit:
- First I went to test this exotic value outside of the switch statement, using an `if` explicitly for this special case/value
- Then I deprecated the use of this value anyway, and completely forbid it in iOS6, as in the latest iOS6 SDK, the `textAlignment` property is now of type `NSTextAlignment` and not `UITextAlignement` but the value `3` (which also matches with `kCTJustifiedTextAlignment` and `NSJustifiedTextAlignment`), is forbidden and will throw an exception at runtime.

The new solution to apply justification to your text is then to add this attribute to your `NSAttributedString` directly (as mentioned by the new depreciation warning I added in my latest commits)

See also #74 that threats this specific point.
