### ISSUE TITLE
how to set a link text?

### ISSUE THREAD

**Issue by stevesz** [AliSoftware/OHAttributedLabel#72]
hi

NSString *text = @"hello world: <   a href="http://www.google.com" > Go < / a  >";
OHAttributedLabel *showText;
........
[showText setAttString: text];
[showText setAllowLinks:YES];
[showText sizeToFit];
[myView addSubview:showText];

Above is my code, I can not get the link function, anybody can tell me what's wrong with it?
It only can get the result: hello world: Go      ---> with plain text, not a hyperlink text

note:
I do not want to use custom link function.  This will make my code complex.

**Comment by AliSoftware** [comment]
OHAttributedLabel works with NSAttributedString (that let you define strings with attributes, like bold, underline, …) and have a method (called `addCustomLink:inRange:`) to add links to the string.
It is not intended to use an HTML string as an input but a NSAttributedString.

Please read the header file and see the example Xcode project, you have everything in the provided example.
