### ISSUE TITLE
Create module for Titanium appcelerator

### ISSUE THREAD

**Issue by ueilat** [AliSoftware/OHAttributedLabel#73]
Have you evaluated Titanium Appcelerator?
one of the bigger gap (without buying expensive modules) is the UiTextLabel with justified text
Any idea or seen project including your class?
thanks

**Comment by AliSoftware** [comment]
Hi ueilat

Yeah already tried Titanium for some of my professionnal projects and really don't like it (in term of flexibility, it does not fit my needs and even if it is aimed to ease the work, in fact in many cases of mine it complexifies it especially in terms on maintenance, we lost multiple days with it on a project on which we had to refactor the architecture…). So I don't plan to create a module for Titanium Appcelerator. At all.

There are plenty of projects including my class (I have about 580 followers on github for it, and plenty of Stackoverflow topics about it too and I receive tons of mails about it). Some of them are even listed in the wiki page.
