### ISSUE TITLE
HighlightedTextColor for UITableViewCell selected row no longer working correctly

### ISSUE THREAD

**Issue by nejj** [AliSoftware/OHAttributedLabel#76]
I just pulled the latest from GitHub after starting a new project and the highlightedtextcolor feature doesn't seem to be working correctly any longer.

The issue:
The color changes to the specified highlighted text color, but stays in the highlighted textcolor even after the row has been deselected.

Test case:
1. Created a custom UITableViewCell with OHAttributedLabel.
2. Select a cell and then proceed to move finger away from the cell to deselect - you will notice the text color is still in the highlighted state.

Not sure if this is of any help but I was using the library (older version which I pulled last week) for a project with no ARC and it was working perfectly fine. The new project I am working on is using ARC so I had to get the latest since it supports ARC.

How I am calling the function:
labelname.highlightedTextColor = [UIColor colorWithWhite:1.0 alpha:1.0];

**Comment by AliSoftware** [comment]
Thanks for the fix!
