### ISSUE TITLE
Color in text does not work 

### ISSUE THREAD

**Issue by arne-diegenbach** [AliSoftware/OHAttributedLabel#80]
I had to comment lines 270 and 490 in OHAttributedLabel.m to fix this.

**Comment by AliSoftware** [comment]
Thanks for the issue.
Actually that is related to the optimization of not making a mutableCopy of the attributedString anymore (to improve performance in TableViews) and we have been discussed this in #79.

I have to find a clean solution to fix this.

**Comment by AliSoftware** [comment]
Just did commit version 1.3.0 that should solve this issue. Please let me kwow if it works better for your case :)
