### ISSUE TITLE
Duplicate string need to set text color

### ISSUE THREAD

**Issue by ghost** [AliSoftware/OHAttributedLabel#81]
I have a string: "test2 & test"

I'd like to change "test" to yellow text But,  the "text2" has changed text color a part expect number "2".

Can anyone help me ?

**Comment by AliSoftware** [comment]
I don't understand your question. How did you change the text color ? (quote some code please)

**Comment by ghost** [comment]
Thanks you for help me. i've resolved this situation. it's my mistake. Please close the issuse
