### ISSUE TITLE
Crashes once I try setting an nsattributestring

### ISSUE THREAD

**Issue by pakmee** [AliSoftware/OHAttributedLabel#85]
CTFramesetterRef framesetter = CTFramesetterCreateWithAttributedString(cfAttrStrWithLinks);

It crashes once I try setting the attribute string...

**Comment by AliSoftware** [comment]
Please provide some code, like the content of your `NSAttributedString` (if it is relevant and crashes with every content even basic one) and how you initialize it, check it is not `nil`, and provide the crash log / thrown exception. Can't help without these.

**Comment by pakmee** [comment]
Hmm seems to be caused by adding an NSMutableAttributedString . It crashes with a bad access here: _framesetter = CTFramesetterCreateWithAttributedString((CFAttributedStringRef)self.attributedString);

**Comment by pakmee** [comment]
Looks like it only takes and NSAttributeString.

**Comment by AliSoftware** [comment]
`attrLabel.attributedText = [NSMutableAttributedString attributedStringWithString:@"Hello"]` works for me and does not crash.

Please provide some code and check the value of the `attributedText` in the debugger before the crashing line. Also are you using ARC or not? I need you to give me more debugging info, code and variable values if you want me to reproduce the bug and help fix it!
