### ISSUE TITLE
EXC_BAD_ACCESS when tapping a link on iOS 6.0.1

### ISSUE THREAD

**Issue by NightIsland** [AliSoftware/OHAttributedLabel#97]
The textFrame gets reset (called from the setNeedsDisplay in touchesBegan) so when the touchesEnded is called, the linkAtPoint returns nil because the CTFrameGetLines returns nil (as the textFrame is nil).

Any ideas why this might be?  I'm building with the latest Xcode, using the latest iOS build and deployment target, running on the iPad 6.0 simulator...

**Comment by AliSoftware** [comment]
Hello @NightIsland and thanks for your issue submission.

May I know why you did close it? Was the issue related to something else in your application and not related to `OHAttributedLabel` at the end? Or did you fix it on your own, and if so how?

Thanks for your feedback

**Comment by NightIsland** [comment]
Hi,

It was solved by using the latest codebase: somehow, I was using an old
version that didn't even support ARC :-)

While I'm here, I'd like to let you know that I'm about to use
OHAttributedLabel in all of my company's products: currently, I'm using
something else but having switched to your class for a few internal test
projects, I like it a great deal and so I'm switching all our apps to use
it.

The next releases of Fanatix, Caught Offside, Vital Football, Tribal
Football, Empire of the Kop and the upcoming V-Sports apps for iPhone, and
the Fanatix and Caught Offside for iPad will use it.

Thanks for a great, lightweight, very customisable and useful component!

Ian Wellock
SVP of Mobile Applications, Fanatix Ltd

From:  AliSoftware notifications@github.com
Reply-To:  AliSoftware/OHAttributedLabel
<reply+i-8247822-666f21e7dbc9cf9d76904037f96b6ab59987e41e-456964@reply.githu
b.com>
Date:  Saturday, 10 November 2012 14:36
To:  AliSoftware/OHAttributedLabel OHAttributedLabel@noreply.github.com
Cc:  Ian Wellock ian@nightisland.com
Subject:  Re: [OHAttributedLabel] EXC_BAD_ACCESS when tapping a link on iOS
6.0.1 (#97)

Hello @NightIsland https://github.com/NightIsland  and thanks for your
issue submission.

May I know why you did close it? Was the issue related to something else in
your application and not related to OHAttributedLabel at the end? Or did you
fix it on your own, and if so how?

Thanks for your feedback

 ‹
 Reply to this email directly or view it on GitHub
<https://github.com/AliSoftware/OHAttributedLabel/issues/97#issuecomment-102
55682> .

**Comment by AliSoftware** [comment]
Thanks a lot!

Glad that my component helps you and you are happy with it :)

I added your softwares to my [dedicated wiki page](https://github.com/AliSoftware/OHAttributedLabel/wiki/They-use-this-class).
